// film
const GET_FILM_REQUEST = "GET_FILM_REQUEST";
const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";
const GET_FILM_ERROR = "GET_FILM_REQUEST";

export { GET_FILM_REQUEST, GET_FILM_SUCCESS, GET_FILM_ERROR };
